---

- name: Install apt packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    pkg: "{{ postgres_packages }}"

- name: Copy configuration file
  become: true
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/12/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0644
  notify: Restart postgres

- name: Copy client authentication configuration file
  become: true
  ansible.builtin.copy:
    src: pg_hba.conf
    dest: /etc/postgresql/12/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0640
  notify: Restart postgres

- name: Create project locale
  become: true
  community.general.locale_gen:
    name: "{{ locale }}"

- name: Create a DB user
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ database_user }}"
    password: "{{ db_pass }}"

- name: Create the database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ database_name }}"
    owner: "{{ database_user }}"
    encoding: UTF8
    lc_ctype: "{{ locale }}"
    lc_collate: "{{ locale }}"
    template: template0
...
