#!/usr/bin/env ansible-playbook
---
- name: Run Ghost locally
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Create Nginx image
      community.docker.docker_image:
        build:
          path: ./nginx
        source: build
        name: tyumentsev4/nginx-ghost
        state: present
        force_source: "{{ force_source | default(false) }}"
        tag: "{{ tag | default('v1') }}"

    - name: Create certs
      ansible.builtin.command: >
        openssl req -new -x509 -nodes
        -out certs/nginx.crt -keyout certs/nginx.key
        -subj '/CN=localhost' -days 365
      args:
        creates: certs/nginx.crt

    - name: Bring up services
      community.docker.docker_compose:
        project_src: .
        state: present
...
