---

- name: Install apt packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    pkg:
      - git
      - libjpeg-dev
      - memcached
      - python3-dev
      - python3-pip
      - python3-venv
      - supervisor

- name: Setup application
  ansible.builtin.include_tasks: setup.yml
- name: Setup django
  ansible.builtin.include_tasks: django.yml
...
